name: Deploy to EC2

on:
  push:
    branches:
      - main  # or use 'master' if that's your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy files to EC2
      run: |
        rsync -avz --delete ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ec2-user/website-temp/

    - name: Copy files to nginx html directory
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "\
          sudo \cp -rf /home/ec2-user/website-temp/* /usr/share/nginx/html/ && \
          sudo systemctl restart nginx"
